# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://josiahls.github.io/"

git_url = "https://github.com/josiahls/character_tracker/tree/master/"

def custom_doc_links(name): return None
